name: Visit URLsUP

on:
  #schedule:
  # - cron: "0 */7 * * *"
  workflow_dispatch:

jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y coreutils curl
          
      - name: Visit URLs
        run: |
          set -e
          # Read the URL list from urls.txt file
          urls=($(cat urls))

          # Loop through the URL list and visit each URL
          for url in "${urls[@]}"
          do
            # Randomly generate a delay time between 2 to 3 minutes
            delay=$(( RANDOM % 120 + 120 ))

            # Send an HTTP request and save the response result
            if response=$(timeout 30s curl -sf -o /dev/null -w '%{http_code}' "$url" || true); then
              if [[ "$response" =~ ^2 ]]; then
                echo "$url : Success"
              else
                echo "$url : Failed"
                echo "URL ${url} failed to visit" >> README.md
              fi
            else
              echo "$url : Failed"
              echo "URL ${url} failed to visit" >> README.md
            fi

            # Wait for the randomly generated delay time before visiting the next URL
            sleep "$delay"
          done

      - name: Check URLs and Update README
        run: |
          # Read the URL list from urls.txt file
          urls=($(cat urls))

          # Loop through the URL list and visit each URL, save the response result to an array variable
          declare -a responses=()
          for url in "${urls[@]}"
          do
            if response=$(timeout 30s curl -sf -o /dev/null -w '%{http_code}' "$url" || true); then
              if [[ "$response" =~ ^2 ]]; then
                responses+=("$url : Success")
              else
                responses+=("$url : Failed")
                echo "URL ${url} failed to visit" >> README.md
              fi
            else
              responses+=("$url : Failed")
              echo "URL ${url} failed to visit" >> README.md
            fi
          done

          # Write the response result to status.md file
          echo "## Website Status" > status.md
          printf '%s\n' "${responses[@]}" >> status.md
          cat README.md | sed '/## Website Status/,$d' > new-readme.md
          cat status.md >> new-readme.md
          mv new-readme.md README.md

          # Push the changes to the remote repository
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update website status"
          git push origin ${{ github.ref }}
