name: Check and Deduplicate URLs
on:
  push:
    branches:
      - main

jobs:
  check_urls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y jq
        
    - name: Check and Deduplicate URLs
      run: |
        # Read the URLs file and remove duplicate lines
        cat urls.txt | sort -u > unique_urls.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add unique_urls.txt
        git commit -m "Remove duplicate URLs"
        git push
