name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update URLs
        run: |
          export README_FILE_PATH="./README.md"
          export URL_FILE_PATH="./urls.txt"

          # Read URLs from file or environment variable
          if [ -f "$URL_FILE_PATH" ]; then
            urls=$(cat "$URL_FILE_PATH")
          elif [ -n "$URLS" ]; then
            urls=$URLS
          else
            echo "ERROR: No URLs found!"
            exit 1
          fi

          for url in $urls
          do
            # Send HTTP request and wait for random delay
            http_status=$(curl -s -o /dev/null -w "%{http_code}" -J -s --retry 3 --retry-delay 5 --retry-max-time 60 --connect-timeout 10 --max-time 30 --speed-time 30 --speed-limit 10240 --jitter 5 "$url")
            delay=$(( RANDOM % 5 + 1 ))
            sleep "$delay"

            # Check HTTP response status code
            if [ $http_status -eq 200 ]; then
              result="成功"
            else
              result="失败"
            fi

            # Output result and append to README file
            echo "| $url | $result |" >> "$README_FILE_PATH"
          done

      - name: Commit changes and push to remote repo
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "Update README.md"
          file_pattern: README.md
