name: LinuxDo Automation

on:
  schedule:
    - cron: "0 */2 * * *" # 每两小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  run-linux-do:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Delay random minutes
      run: |
        delay=$((RANDOM % 2 + 1))
        echo "Sleeping for $delay minutes..."
        sleep "${delay}m"

    - name: Run Linux_do.py script
      env:
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
      run: python tools/Linux_do.py
