name: LinuxDo Automation

on:
  schedule:
    - cron: "0 */2 * * *" # 每三小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  run-linux-do:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables from secrets
      run: |
        echo "LINUXDO_USERNAME=${{ secrets.LINUXDO_USERNAME }}" >> $GITHUB_ENV
        echo "LINUXDO_PASSWORD=${{ secrets.LINUXDO_PASSWORD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install selenium

    - name: Delay random minutes
      run: |
        delay=$((RANDOM % 2 + 1))
        echo "Sleeping for $delay minutes..."
        sleep "${delay}m"

    - name: Run Linux_do.py script
      run: |
        python3 tools/Linux_do.py
      env:
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
