name: Visit URLs

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:
jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        run: |
          curl -f https://veg.linlim.repl.co
          curl -f https://ko.limkco.repl.co
          curl -f https://litv.yoyholee.repl.co
          curl -f https://v2ray.yoyho.repl.co
          curl -f https://V2.sukure.repl.co
          curl -f https://rray.chavir.repl.co
          curl -f https://tote.kaikaixin.repl.co
          curl -f https://k2.shilh.repl.co
