name: Visit URLs

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:
jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        run: |
          curl -f veg.linlim.repl.co
          curl -f ko.limkco.repl.co
          curl -f litv.yoyholee.repl.co
          curl -f v2ray.yoyho.repl.co
          curl -f V2.sukure.repl.co
          curl -f rray.chavir.repl.co
          curl -f tote.kaikaixin.repl.co
          curl -f k2.shilh.repl.co
          branch: master
