name: Visit URLs

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        run: |
          urls=(
            "https://www.google.com"
            "https://www.github.com"
          )
          for url in "${urls[@]}"
          do
            curl -f "$url"
          done

