name: Visit URLs

on:
  schedule:
    - cron: "* */7 * * *"
  workflow_dispatch:

jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        run: |
          # 读取 urls 文件中的 URL 列表并保存到数组中
          urls=($(cat urls))

          for url in "${urls[@]}"
          do
            # 随机生成一个 1~5 秒之间的延迟时间
            delay=$(( RANDOM % 5 + 1 ))

            # 发送 HTTP 请求并保存响应结果
            curl -f -m 10 "$url"

            # 检查 curl 命令的退出码
            if [ $? -ne 0 ]; then
              echo "URL ${url} 访问失败"
            fi

            # 在访问下一个URL 前等待随机生成的延迟时间
            sleep "$delay"
          done
