name: Visit URLs

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        env:
          README_FILE_PATH: "./README.md"
        run: |
          urls=(
            "https://veg.linlim.repl.co"
            "https://ko.limkco.repl.co"
            "https://litv.yoyholee.repl.co"
            "https://v2ray.yoyho.repl.co"
            "https://V2.sukure.repl.co"
            "https://rray.chavir.repl.co"
            "https://tote.kaikaixin.repl.co"
            "http://k2.shilh.repl.co"
          )
          for url in "${urls[@]}"
          do
            # 随机生成一个 1~5 秒之间的延迟时间
            delay=$(( RANDOM % 5 + 1 ))

            # 发送 HTTP 请求并保存响应结果
            http_status=$(curl -s -o /dev/null -w "%{http_code}" -m 10 "$url")
            
            # 检查 HTTP 响应状态码
            if [ $http_status -eq 200 ]; then
              result="成功"
            else
              result="失败"
            fi
            
            # 输出结果并将其保存到 README.md 文件中
            echo "| $url | $result |" >> "$README_FILE_PATH"

            # 在访问下一个 URL 前等待随机生成的延迟时间
            sleep "$delay"
          done
