name: Visit URLs

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  visit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Visit URLs
        run: |
          urls=(
            “https://veg.linlim.repl.co”
            “https://ko.limkco.repl.co”
            “https://litv.yoyholee.repl.co”
            “https://v2ray.yoyho.repl.co”
            “https://V2.sukure.repl.co”
            “https://rray.chavir.repl.co”
            “https://tote.kaikaixin.repl.co”
            “https://k2.shilh.repl.co”
          )
          for url in "${urls[@]}"
          do
            curl -f "$url"
          done

