name: Monitor and Obfuscate JS

on:
  push:
    branches:
      - main
  # 允许手动触发
  workflow_dispatch:

jobs:
  obfuscate-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史，避免分支识别错误

      - name: Get current branch
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install JavaScript Obfuscator
        run: npm install -g javascript-obfuscator

      - name: Create output directory
        run: mkdir -p output

      - name: Obfuscate JavaScript files
        run: |
          mkdir -p output
          if [ -d "input" ] && [ "$(ls -A input/*.js 2>/dev/null)" ]; then
            for file in input/*.js; do
              filename=$(basename "$file")
              javascript-obfuscator "$file" --output "output/$filename" \
                --compact true \
                --control-flow-flattening true \
                --dead-code-injection true \
                --identifier-names-generator hexadecimal \
                --rename-globals true \
                --string-array true \
                --string-array-encoding 'rc4' \
                --string-array-threshold 1 \
                --transform-object-keys true \
                --unicode-escape-sequence true
              echo "✅ Obfuscated $file -> output/$filename"
            done
          else
            echo "⚠️ No JavaScript files found in input/ directory. Skipping obfuscation."
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ env.CURRENT_BRANCH }}  # 直接获取当前分支名
          commit_message: "Auto-obfuscated JavaScript files"
          push_options: --force
