name: Visit URLs

on:
  schedule:
    - cron: '*/50 * * * *'
      workflow_dispatch:

jobs:
  visit_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove duplicate URLs
        run: python ./tools/remove_duplicates.py ${{ github.workspace }}/urls

      - name: Delay random minutes
        run: |
          delay=$((RANDOM % 9 + 1))
          sleep "$delay"
          
      - name: Check and create 'urls' file
        run: |
          if [ ! -f "urls" ]; then
            touch urls
          fi

      - name: Visit URLs
        run: |
          set -e
          urls=($(cat urls | shuf))
          declare -a responses=()
          declare -a failed_urls=()
          for url in "${urls[@]}"; do
            # 执行原始的 curl 请求，并处理响应
            response=$(timeout 5s curl -sf -o /dev/null -w '%{http_code}\n' "$url" || echo "Failed")
            if [[ "$response" =~ ^[23] ]]; then
              echo "$url: 成功"
              responses+=("$url: 成功")
            else
              echo "$url: 失败 ($response)"
              responses+=("$url: 失败 ($response)")
              failed_urls+=("$url: 失败 ($response)")
            fi
            echo ""
          done

          # Push failed URLs to README.md
          echo "# 失败网址" > README.md
          for failed_url in "${failed_urls[@]}"; do
            echo "- $failed_url" >> README.md
          done
          
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update failed URLs" -q
          git push
