name: Visit URLsII

on:
  schedule:
    - cron: '0 13-23/2 * * *'
    - cron: '25 0-12/1 * * *'
  workflow_dispatch:

jobs:
  visit_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove duplicate URLs
        run: python remove_duplicates.py urls

      - name: Delay random minutes
        run: |
          delay=$((RANDOM % 9 + 1))
          sleep "$delay"

      - name: Visit URLs
        run: |
          set -e
          urls=($(cat urls | shuf))

          declare -a responses=()
          declare -a failed_urls=()

          for url in "${urls[@]}"; do
            response=$(timeout 5s curl -sf -o /dev/null -w '%{http_code}\n' "$url" || echo "Failed")
            if [[ "$response" =~ ^[23] ]]; then
              echo "$url: 成功"
              responses+=("$url: 成功")
            else
              echo "$url: 失败 ($response)"
              responses+=("$url: 失败 ($response)")
              failed_urls+=("$url: 失败 ($response)")
            fi
            echo ""
          done

          # Push failed URLs to README.md
          echo "# 失败网址" > README.md
          for failed_url in "${failed_urls[@]}"; do
            echo "- $failed_url" >> README.md
          done

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update failed URLs"
          git push
