name: Test

on:
 # schedule:
 #  - cron: '*/50 */12 * * *'
      workflow_dispatch:

jobs:
  visit_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove duplicate URLs
        run: python ./tools/bludweb.py webs 3
      
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update failed URLs" -q
          git push
