name: Download and Write File

on:
  schedule:
       - cron: '35 * */7 * *' 
  workflow_dispatch:

jobs:
  download_and_write:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download File
        run: |
          curl -o litme https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3QvcyFBbzF3c0NzSmFEMk9mOTZsbS1iT1A2NGVrOGc_ZT1uZDZnZ2M
          ls -l litme

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add litme
          git commit -m "Update litme file"
          git push
